services:
  reminder-service:
    container_name: reminder-service
    build:
      context: ./
    ports:
      - "8081:8081"
    restart: on-failure
    env_file:
      - configs/cfg.env
    networks:
      - shared_network

volumes:
  db-data:
    external: true

networks:
  shared_network:
    external: true
